// <auto-generated />
using System;
using ATI_IEC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ATI_IEC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ATI_IEC.Models.IecDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IecDocuments");
                });

            modelBuilder.Entity("ATI_IEC.Models.KpsRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AudioRecording")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Bag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BagQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Banner")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BannerQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BlackWhite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlackWhiteQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Book")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Boxing")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoxingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CallingCard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CallingCardQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Certificate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CertificateQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cutting")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CuttingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Fan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FanQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Folding")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoldingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FullColor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FullColorQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ISBN")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ISSN")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Manual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManualQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Notebook")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotebookQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Notepad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NotepadQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Others")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PdfPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Pen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PenQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PerfectBinding")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerfectBindingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PhotoCoverage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Program")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProgramQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Report")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReportQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RingBinding")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RingBindingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Sorting")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortingQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("VideoRecording")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VideoSoundSetup")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VideoStreaming")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("KpsRequests");
                });

            modelBuilder.Entity("ATI_IEC.Models.UserReader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserReaders");
                });
#pragma warning restore 612, 618
        }
    }
}
